sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install

script:
  - cd ui-kit
  - npm install
  - npm install -g @angular/cli
  - npm run test-components
  - npm run build-components
